name: rss_feed_example
description: Demonstrates how to use the rss_feed package.
publish_to: 'none' # This example is not intended for publishing to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0' # Ensure this matches your package's flutter environment minimum

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  lottie: ^3.1.2
  share_plus: ^10.0.3
  # The package you are demonstrating
  rss_feed:
    path: .. # Corrected path from '../' to '..'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Note: This is the example's lint version, not the main package's.

flutter:
  assets:
    - assets/feed_list.jpeg
    - assets/feed_detail.jpeg
    - assets/article_detail.jpeg
    - assets/web_view.jpeg